# Generated by Django 6.0.3 on 2026-04-06 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Muito baixo'), (2, 'Baixo'), (3, 'Médio'), (4, 'Alto'), (5, 'Muito alto')], default=3)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('link_pagina', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano_inicio', models.IntegerField()),
                ('ano_fim', models.IntegerField(blank=True, null=True)),
                ('universidade', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Licenciatura',
                'verbose_name_plural': 'Licenciaturas',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('ano', models.PositiveSmallIntegerField()),
                ('conceitos_aplicados', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/imagens/')),
                ('video_demo', models.URLField(blank=True)),
                ('link_repositorio', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('em_curso', 'Em curso'), ('concluido', 'Concluído')], default='em_curso', max_length=20)),
                ('autor', models.CharField(max_length=200)),
                ('competencias', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.competencia')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/logos/')),
                ('link_oficial', models.URLField(blank=True)),
                ('nivel_interesse', models.PositiveSmallIntegerField(choices=[(1, 'Muito baixo'), (2, 'Baixo'), (3, 'Médio'), (4, 'Alto'), (5, 'Muito alto')], default=3)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('entidade_formadora', models.CharField(max_length=200)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='formacoes/certificados/')),
                ('descricao', models.TextField(blank=True)),
                ('competencias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.competencia')),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
            },
        ),
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('etapa', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='makingof/fotos/')),
                ('decisao', models.TextField(blank=True)),
                ('erros', models.TextField(blank=True)),
                ('uso_IA', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='making_ofs', to='portfolio.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, help_text='Use Ctrl (ou Command) para selecionar várias tecnologias. Os itens destacados estão selecionados.', related_name='competencias', to='portfolio.tecnologia'),
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('semestre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ano', models.PositiveSmallIntegerField()),
                ('ects', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(blank=True, choices=[('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=50)),
                ('natureza', models.CharField(blank=True, max_length=50)),
                ('objetivos', models.TextField(blank=True)),
                ('programa', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='uc/imagens/')),
                ('docentes', models.ManyToManyField(blank=True, related_name='unidades_curriculares', to='portfolio.docente')),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_curriculares', to='portfolio.licenciatura')),
            ],
            options={
                'verbose_name': 'Unidade Curricular',
                'verbose_name_plural': 'Unidades Curriculares',
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='unidade_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='portfolio.unidadecurricular'),
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('quizz', 'Quizz'), ('teste', 'Teste'), ('projeto', 'Projeto'), ('defesa', 'Defesa'), ('exame_recurso', 'Exame Recurso'), ('nota_final', 'Nota Final')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('formacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classificacoes', to='portfolio.formacao')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='portfolio.projeto')),
                ('unidade_curricular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='portfolio.unidadecurricular')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
            },
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('projeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.projeto')),
                ('resumo', models.TextField(blank=True)),
                ('palavras_chave', models.CharField(blank=True, max_length=300)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('orientadores', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.docente')),
            ],
            bases=('portfolio.projeto',),
        ),
    ]
