# Generated by Django 6.0.3 on 2026-04-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_tfc_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tecnologia',
            name='tipo',
        ),
    ]
