# Generated by Django 6.0.3 on 2026-04-29 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_tipotecnologia_remove_tecnologia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.tipotecnologia'),
        ),
    ]
