# Generated by Django 6.0.3 on 2026-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tecnologia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao',
            name='nome',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=1000),
        ),
    ]
