# Generated by Django 6.0.3 on 2026-05-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_formacao_nome_alter_projeto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='tipo',
            field=models.CharField(choices=[('quizz', 'Quizz'), ('teste', 'Teste'), ('projeto', 'Projeto'), ('defesa', 'Defesa'), ('exame_recurso', 'Exame Recurso'), ('nota_final', 'Nota Final')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='nome',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nome',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='formacao',
            name='entidade_formadora',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='nome',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='universidade',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='makingof',
            name='etapa',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='autor',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='estado',
            field=models.CharField(choices=[('em_curso', 'Em curso'), ('concluido', 'Concluído')], default='em_curso', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='nome',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='area',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='palavras_chave',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='unidadecurricular',
            name='codigo',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadecurricular',
            name='natureza',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='unidadecurricular',
            name='nome',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='unidadecurricular',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=1000),
        ),
    ]
